source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'whawhawhatLib_Example', :exclusive => true do
  pod 'whawhawhatLib', :path => '../'
end

target 'whawhawhatLib_Tests', :exclusive => true do
  pod 'whawhawhatLib', :path => '../'

  
end
